server:
  port: 8082

spring:
  application:
    name: video-service
  config:
    import: optional:configserver:http://localhost:8888 # ALTERADO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ALTERADO