server:
  port: 8084

spring:
  application:
    name: catalog-service

spring:
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
