version: '3.9'

services:

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_REPO=file:///config-repo
    volumes:
      - ./config-repo:/config-repo
    networks:
      - luce-net

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - luce-net

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - luce-net

  video-service:
    build: ./video-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - luce-net

  catalog-service:
    build: ./catalog-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - luce-net

networks:
  luce-net:
    driver: bridge
