services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - luce-network

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=file:/config-repo
    networks:
      - luce-network
    depends_on:
      - discovery-server
    restart: on-failure

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - luce-network
    depends_on:
      - config-server
      - discovery-server
    restart: on-failure

  video-service:
    build: ./video-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - luce-network
    depends_on:
      - config-server
      - discovery-server
    restart: on-failure

  catalog-service:
    build: ./catalog-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - luce-network
    depends_on:
      - config-server
      - discovery-server
    restart: on-failure

  # --- BLOCO DE CÓDIGO ADICIONADO ABAIXO ---
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080" # A porta de entrada para o front-end
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - luce-network
    depends_on:
      - config-server
      - discovery-server
    restart: on-failure

networks:
  luce-network:
    driver: bridge