server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1 # <-- CORRIGIDO DE 2 PARA 1

        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/api/videos/**
          filters:
            - StripPrefix=1 # <-- CORRIGIDO DE 2 PARA 1

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=1 # <-- CORRIGIDO DE 2 PARA 1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/