server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo
        git:
          enabled: false
    discovery:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
