# Nome do workflow que aparecerá no separador "Actions" do seu GitHub
name: Build, Test and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test: # Alterado o nome do job para ser mais descritivo
    runs-on: ubuntu-latest

    steps:
      # 1. Descarrega o seu código do repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura o ambiente Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # --- ETAPA DE TESTE EXPLÍCITA ---
      # 3. (CI) Executa os testes para todos os módulos
      - name: Run tests with Maven
        run: mvn test

      # --- ETAPA DE CONSTRUÇÃO (APENAS SE OS TESTES PASSAREM) ---
      # 4. (CI) Empacota as aplicações (cria os ficheiros .jar)
      - name: Package applications with Maven
        run: mvn package -DskipTests

      # 5. Faz o login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. (CD) Constrói e envia a imagem Docker de cada microserviço
      - name: Build and push config-server image
        uses: docker/build-push-action@v4
        with:
          context: ./config-server
          push: true
          tags: lourencosp/luce-config-server:latest

      - name: Build and push discovery-server image
        uses: docker/build-push-action@v4
        with:
          context: ./discovery-server
          push: true
          tags: lourencosp/luce-discovery-server:latest

      - name: Build and push auth-service image
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: lourencosp/luce-auth-service:latest

      - name: Build and push video-service image
        uses: docker/build-push-action@v4
        with:
          context: ./video-service
          push: true
          tags: lourencosp/luce-video-service:latest

      - name: Build and push catalog-service image
        uses: docker/build-push-action@v4
        with:
          context: ./catalog-service
          push: true
          tags: lourencosp/luce-catalog-service:latest

      - name: Build and push gateway-service image
        uses: docker/build-push-action@v4
        with:
          context: ./gateway-service
          push: true
          tags: lourencosp/luce-gateway-service:latest

      # Não se esqueça de adicionar o frontend-service aqui também
      - name: Build and push frontend-service image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-service
          push: true
          tags: lourencosp/luce-frontend-service:latest